// This file is auto-generated by @hey-api/openapi-ts

export const ActionStatusSchema = {
    type: 'string',
    enum: ['open', 'in_progress', 'closed'],
    title: 'ActionStatus'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DemoSeedRequestSchema = {
    properties: {
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        from_time: {
            type: 'string',
            format: 'date-time',
            title: 'From Time'
        },
        to_time: {
            type: 'string',
            format: 'date-time',
            title: 'To Time'
        }
    },
    type: 'object',
    required: ['machine_id', 'from_time', 'to_time'],
    title: 'DemoSeedRequest'
} as const;

export const DepartmentCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DepartmentCreate'
} as const;

export const DepartmentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'DepartmentPublic'
} as const;

export const DepartmentTileSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        oee: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OEESummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        unit_count: {
            type: 'integer',
            title: 'Unit Count',
            default: 0
        },
        machine_count: {
            type: 'integer',
            title: 'Machine Count',
            default: 0
        },
        running_count: {
            type: 'integer',
            title: 'Running Count',
            default: 0
        },
        warning_count: {
            type: 'integer',
            title: 'Warning Count',
            default: 0
        },
        stopped_count: {
            type: 'integer',
            title: 'Stopped Count',
            default: 0
        },
        alarm_count: {
            type: 'integer',
            title: 'Alarm Count',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'DepartmentTile'
} as const;

export const DepartmentUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Order'
        }
    },
    type: 'object',
    title: 'DepartmentUpdate'
} as const;

export const EventSeveritySchema = {
    type: 'string',
    enum: ['info', 'low', 'medium', 'high', 'critical'],
    title: 'EventSeverity'
} as const;

export const EventSourceSchema = {
    type: 'string',
    enum: ['operator', 'system', 'integration'],
    title: 'EventSource'
} as const;

export const EventStatusSchema = {
    type: 'string',
    enum: ['active', 'acknowledged', 'cleared'],
    title: 'EventStatus'
} as const;

export const EventTypeSchema = {
    type: 'string',
    enum: ['operator_note', 'alarm', 'warning', 'maintenance', 'quality', 'production', 'order_change', 'system', 'alarm_cleared'],
    title: 'EventType'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HierarchyLevelSchema = {
    type: 'string',
    enum: ['home', 'department', 'unit', 'machine'],
    title: 'HierarchyLevel'
} as const;

export const HierarchyViewCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        level: {
            '$ref': '#/components/schemas/HierarchyLevel'
        },
        view_type: {
            type: 'string',
            maxLength: 100,
            title: 'View Type',
            default: 'placeholder'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        entity_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Id'
        }
    },
    type: 'object',
    required: ['name', 'level'],
    title: 'HierarchyViewCreate'
} as const;

export const HierarchyViewPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        level: {
            '$ref': '#/components/schemas/HierarchyLevel'
        },
        view_type: {
            type: 'string',
            maxLength: 100,
            title: 'View Type',
            default: 'placeholder'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        is_default: {
            type: 'boolean',
            title: 'Is Default',
            default: false
        },
        entity_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'level', 'id'],
    title: 'HierarchyViewPublic'
} as const;

export const HierarchyViewUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        view_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'View Type'
        },
        display_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Order'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Default'
        }
    },
    type: 'object',
    title: 'HierarchyViewUpdate'
} as const;

export const HierarchyViewsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/HierarchyViewPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'HierarchyViewsPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LossCodeCategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Type Id'
        }
    },
    type: 'object',
    required: ['name', 'type_id'],
    title: 'LossCodeCategoryCreate'
} as const;

export const LossCodeCategoryInHierarchySchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Type Id'
        },
        loss_codes: {
            items: {
                '$ref': '#/components/schemas/LossCodeInHierarchy'
            },
            type: 'array',
            title: 'Loss Codes',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id', 'type_id'],
    title: 'LossCodeCategoryInHierarchy'
} as const;

export const LossCodeCategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Type Id'
        }
    },
    type: 'object',
    required: ['name', 'id', 'type_id'],
    title: 'LossCodeCategoryPublic'
} as const;

export const LossCodeCategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        display_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Order'
        }
    },
    type: 'object',
    title: 'LossCodeCategoryUpdate'
} as const;

export const LossCodeCreateSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Code'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['code', 'name', 'category_id'],
    title: 'LossCodeCreate'
} as const;

export const LossCodeEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LossCodeEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LossCodeEntriesPublic'
} as const;

export const LossCodeEntryCreateSchema = {
    properties: {
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        loss_code_id: {
            type: 'string',
            format: 'uuid',
            title: 'Loss Code Id'
        }
    },
    type: 'object',
    required: ['start_time', 'machine_id', 'loss_code_id'],
    title: 'LossCodeEntryCreate'
} as const;

export const LossCodeEntryPublicSchema = {
    properties: {
        start_time: {
            type: 'string',
            format: 'date-time',
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        loss_code_id: {
            type: 'string',
            format: 'uuid',
            title: 'Loss Code Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['start_time', 'id', 'machine_id', 'loss_code_id', 'created_at'],
    title: 'LossCodeEntryPublic'
} as const;

export const LossCodeEntryUpdateSchema = {
    properties: {
        start_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Time'
        },
        end_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Time'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        loss_code_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Loss Code Id'
        }
    },
    type: 'object',
    title: 'LossCodeEntryUpdate'
} as const;

export const LossCodeInHierarchySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name'],
    title: 'LossCodeInHierarchy'
} as const;

export const LossCodePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        category_id: {
            type: 'string',
            format: 'uuid',
            title: 'Category Id'
        }
    },
    type: 'object',
    required: ['id', 'code', 'name', 'category_id'],
    title: 'LossCodePublic'
} as const;

export const LossCodeTypePublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Key'
        },
        label: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Label'
        },
        color: {
            type: 'string',
            maxLength: 20,
            title: 'Color',
            default: '#6B7280'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['key', 'label', 'id'],
    title: 'LossCodeTypePublic'
} as const;

export const LossCodeTypeWithHierarchySchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Key'
        },
        label: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Label'
        },
        color: {
            type: 'string',
            maxLength: 20,
            title: 'Color',
            default: '#6B7280'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/LossCodeCategoryInHierarchy'
            },
            type: 'array',
            title: 'Categories',
            default: []
        }
    },
    type: 'object',
    required: ['key', 'label', 'id'],
    title: 'LossCodeTypeWithHierarchy'
} as const;

export const LossCodeUpdateSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        category_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category Id'
        }
    },
    type: 'object',
    title: 'LossCodeUpdate'
} as const;

export const LossCodesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LossCodePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LossCodesPublic'
} as const;

export const MachineActionCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        status: {
            '$ref': '#/components/schemas/ActionStatus',
            default: 'open'
        },
        owner: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Owner'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        }
    },
    type: 'object',
    required: ['title', 'owner', 'machine_id'],
    title: 'MachineActionCreate'
} as const;

export const MachineActionPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        status: {
            '$ref': '#/components/schemas/ActionStatus',
            default: 'open'
        },
        owner: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Owner'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'owner', 'id', 'machine_id', 'created_at'],
    title: 'MachineActionPublic'
} as const;

export const MachineActionUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ActionStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        owner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner'
        }
    },
    type: 'object',
    title: 'MachineActionUpdate'
} as const;

export const MachineActionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MachineActionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MachineActionsPublic'
} as const;

export const MachineCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        kep_tag_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kep Tag Prefix'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        machine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Machine Type'
        },
        unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['name', 'unit_id'],
    title: 'MachineCreate'
} as const;

export const MachineEventCreateSchema = {
    properties: {
        event_type: {
            '$ref': '#/components/schemas/EventType',
            default: 'operator_note'
        },
        severity: {
            '$ref': '#/components/schemas/EventSeverity',
            default: 'info'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        source: {
            '$ref': '#/components/schemas/EventSource',
            default: 'operator'
        },
        status: {
            '$ref': '#/components/schemas/EventStatus',
            default: 'active'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        related_action_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Related Action Id'
        }
    },
    type: 'object',
    required: ['title', 'machine_id'],
    title: 'MachineEventCreate'
} as const;

export const MachineEventPublicSchema = {
    properties: {
        event_type: {
            '$ref': '#/components/schemas/EventType',
            default: 'operator_note'
        },
        severity: {
            '$ref': '#/components/schemas/EventSeverity',
            default: 'info'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        source: {
            '$ref': '#/components/schemas/EventSource',
            default: 'operator'
        },
        status: {
            '$ref': '#/components/schemas/EventStatus',
            default: 'active'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        related_action_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Related Action Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'machine_id'],
    title: 'MachineEventPublic'
} as const;

export const MachineEventUpdateSchema = {
    properties: {
        event_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventType'
                },
                {
                    type: 'null'
                }
            ]
        },
        severity: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventSeverity'
                },
                {
                    type: 'null'
                }
            ]
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        source: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventSource'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/EventStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        related_action_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Related Action Id'
        }
    },
    type: 'object',
    title: 'MachineEventUpdate'
} as const;

export const MachineEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MachineEventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MachineEventsPublic'
} as const;

export const MachineNoteCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        content: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'Content'
        },
        shift: {
            '$ref': '#/components/schemas/NoteShift'
        },
        impact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Impact'
        },
        criticality: {
            '$ref': '#/components/schemas/NoteCriticality',
            default: 'low'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        }
    },
    type: 'object',
    required: ['title', 'content', 'shift', 'machine_id'],
    title: 'MachineNoteCreate'
} as const;

export const MachineNotePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        content: {
            type: 'string',
            maxLength: 5000,
            minLength: 1,
            title: 'Content'
        },
        shift: {
            '$ref': '#/components/schemas/NoteShift'
        },
        impact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Impact'
        },
        criticality: {
            '$ref': '#/components/schemas/NoteCriticality',
            default: 'low'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'content', 'shift', 'id', 'machine_id', 'created_at'],
    title: 'MachineNotePublic'
} as const;

export const MachineNoteUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        content: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        shift: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/NoteShift'
                },
                {
                    type: 'null'
                }
            ]
        },
        impact: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Impact'
        },
        criticality: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/NoteCriticality'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'MachineNoteUpdate'
} as const;

export const MachineNotesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MachineNotePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MachineNotesPublic'
} as const;

export const MachinePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        kep_tag_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kep Tag Prefix'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        machine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Machine Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['name', 'id', 'unit_id'],
    title: 'MachinePublic'
} as const;

export const MachineStatusPublicSchema = {
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        },
        status: {
            '$ref': '#/components/schemas/OEEStatus'
        },
        availability: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Availability'
        },
        performance: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Performance'
        },
        quality: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Quality'
        },
        raw_data: {
            anyOf: [
                {},
                {
                    type: 'null'
                }
            ],
            title: 'Raw Data'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        machine_id: {
            type: 'string',
            format: 'uuid',
            title: 'Machine Id'
        }
    },
    type: 'object',
    required: ['status', 'availability', 'performance', 'quality', 'id', 'machine_id'],
    title: 'MachineStatusPublic'
} as const;

export const MachineStatusesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MachineStatusPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MachineStatusesPublic'
} as const;

export const MachineTileSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        kep_tag_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kep Tag Prefix'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        machine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Machine Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        unit_id: {
            type: 'string',
            format: 'uuid',
            title: 'Unit Id'
        },
        oee: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OEESummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        active_alarm_count: {
            type: 'integer',
            title: 'Active Alarm Count',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'id', 'unit_id'],
    title: 'MachineTile'
} as const;

export const MachineUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        kep_tag_prefix: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kep Tag Prefix'
        },
        display_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Order'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        },
        machine_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Machine Type'
        }
    },
    type: 'object',
    title: 'MachineUpdate'
} as const;

export const MachinesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MachinePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MachinesPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NoteCriticalitySchema = {
    type: 'string',
    enum: ['low', 'medium', 'high'],
    title: 'NoteCriticality'
} as const;

export const NoteShiftSchema = {
    type: 'string',
    enum: ['morning', 'afternoon', 'night'],
    title: 'NoteShift'
} as const;

export const OEEStatusSchema = {
    type: 'string',
    enum: ['green', 'yellow', 'red'],
    title: 'OEEStatus'
} as const;

export const OEESummarySchema = {
    properties: {
        availability: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Availability'
        },
        performance: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Performance'
        },
        quality: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quality'
        },
        availability_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OEEStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        performance_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OEEStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        quality_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OEEStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'OEESummary'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnitCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        department_id: {
            type: 'string',
            format: 'uuid',
            title: 'Department Id'
        }
    },
    type: 'object',
    required: ['name', 'department_id'],
    title: 'UnitCreate'
} as const;

export const UnitPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        department_id: {
            type: 'string',
            format: 'uuid',
            title: 'Department Id'
        }
    },
    type: 'object',
    required: ['name', 'id', 'department_id'],
    title: 'UnitPublic'
} as const;

export const UnitTileSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            type: 'integer',
            title: 'Display Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        department_id: {
            type: 'string',
            format: 'uuid',
            title: 'Department Id'
        },
        oee: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/OEESummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        machine_count: {
            type: 'integer',
            title: 'Machine Count',
            default: 0
        },
        running_count: {
            type: 'integer',
            title: 'Running Count',
            default: 0
        },
        warning_count: {
            type: 'integer',
            title: 'Warning Count',
            default: 0
        },
        stopped_count: {
            type: 'integer',
            title: 'Stopped Count',
            default: 0
        },
        alarm_count: {
            type: 'integer',
            title: 'Alarm Count',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'id', 'department_id'],
    title: 'UnitTile'
} as const;

export const UnitUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        display_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Display Order'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        }
    },
    type: 'object',
    title: 'UnitUpdate'
} as const;

export const UnitsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UnitPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UnitsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;