// This file is auto-generated by @hey-api/openapi-ts

export type ActionStatus = 'open' | 'in_progress' | 'closed';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DemoSeedRequest = {
    machine_id: string;
    from_time: string;
    to_time: string;
};

export type DepartmentCreate = {
    name: string;
    description?: (string | null);
    display_order?: number;
};

export type DepartmentPublic = {
    name: string;
    description?: (string | null);
    display_order?: number;
    id: string;
};

export type DepartmentTile = {
    name: string;
    description?: (string | null);
    display_order?: number;
    id: string;
    oee?: (OEESummary | null);
    unit_count?: number;
    machine_count?: number;
    running_count?: number;
    warning_count?: number;
    stopped_count?: number;
    alarm_count?: number;
};

export type DepartmentUpdate = {
    name?: (string | null);
    description?: (string | null);
    display_order?: (number | null);
};

export type EventSeverity = 'info' | 'low' | 'medium' | 'high' | 'critical';

export type EventSource = 'operator' | 'system' | 'integration';

export type EventStatus = 'active' | 'acknowledged' | 'cleared';

export type EventType = 'operator_note' | 'alarm' | 'warning' | 'maintenance' | 'quality' | 'production' | 'order_change' | 'system' | 'alarm_cleared';

export type HierarchyLevel = 'home' | 'department' | 'unit' | 'machine';

export type HierarchyViewCreate = {
    name: string;
    level: HierarchyLevel;
    view_type?: string;
    display_order?: number;
    is_default?: boolean;
    entity_id?: (string | null);
};

export type HierarchyViewPublic = {
    name: string;
    level: HierarchyLevel;
    view_type?: string;
    display_order?: number;
    is_default?: boolean;
    entity_id?: (string | null);
    id: string;
};

export type HierarchyViewsPublic = {
    data: Array<HierarchyViewPublic>;
    count: number;
};

export type HierarchyViewUpdate = {
    name?: (string | null);
    view_type?: (string | null);
    display_order?: (number | null);
    is_default?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LossCodeCategoryCreate = {
    name: string;
    display_order?: number;
    type_id: string;
};

export type LossCodeCategoryInHierarchy = {
    name: string;
    display_order?: number;
    id: string;
    type_id: string;
    loss_codes?: Array<LossCodeInHierarchy>;
};

export type LossCodeCategoryPublic = {
    name: string;
    display_order?: number;
    id: string;
    type_id: string;
};

export type LossCodeCategoryUpdate = {
    name?: (string | null);
    display_order?: (number | null);
};

export type LossCodeCreate = {
    code: string;
    name: string;
    category_id: string;
};

export type LossCodeEntriesPublic = {
    data: Array<LossCodeEntryPublic>;
    count: number;
};

export type LossCodeEntryCreate = {
    start_time: string;
    end_time?: (string | null);
    notes?: (string | null);
    machine_id: string;
    loss_code_id: string;
};

export type LossCodeEntryPublic = {
    start_time: string;
    end_time?: (string | null);
    notes?: (string | null);
    id: string;
    machine_id: string;
    loss_code_id: string;
    created_by?: (string | null);
    created_at: string;
};

export type LossCodeEntryUpdate = {
    start_time?: (string | null);
    end_time?: (string | null);
    notes?: (string | null);
    loss_code_id?: (string | null);
};

export type LossCodeInHierarchy = {
    id: string;
    code: string;
    name: string;
};

export type LossCodePublic = {
    id: string;
    code: string;
    name: string;
    category_id: string;
};

export type LossCodesPublic = {
    data: Array<LossCodePublic>;
    count: number;
};

export type LossCodeTypePublic = {
    key: string;
    label: string;
    color?: string;
    display_order?: number;
    id: string;
};

export type LossCodeTypeWithHierarchy = {
    key: string;
    label: string;
    color?: string;
    display_order?: number;
    id: string;
    categories?: Array<LossCodeCategoryInHierarchy>;
};

export type LossCodeUpdate = {
    code?: (string | null);
    name?: (string | null);
    category_id?: (string | null);
};

export type MachineActionCreate = {
    title: string;
    status?: ActionStatus;
    owner: string;
    machine_id: string;
};

export type MachineActionPublic = {
    title: string;
    status?: ActionStatus;
    owner: string;
    id: string;
    machine_id: string;
    created_by?: (string | null);
    created_at: string;
};

export type MachineActionsPublic = {
    data: Array<MachineActionPublic>;
    count: number;
};

export type MachineActionUpdate = {
    title?: (string | null);
    status?: (ActionStatus | null);
    owner?: (string | null);
};

export type MachineCreate = {
    name: string;
    description?: (string | null);
    kep_tag_prefix?: (string | null);
    display_order?: number;
    machine_type?: (string | null);
    unit_id: string;
};

export type MachineEventCreate = {
    event_type?: EventType;
    severity?: EventSeverity;
    title: string;
    description?: (string | null);
    source?: EventSource;
    status?: EventStatus;
    timestamp?: string;
    machine_id: string;
    related_action_id?: (string | null);
};

export type MachineEventPublic = {
    event_type?: EventType;
    severity?: EventSeverity;
    title: string;
    description?: (string | null);
    source?: EventSource;
    status?: EventStatus;
    timestamp?: string;
    id: string;
    machine_id: string;
    created_by?: (string | null);
    related_action_id?: (string | null);
};

export type MachineEventsPublic = {
    data: Array<MachineEventPublic>;
    count: number;
};

export type MachineEventUpdate = {
    event_type?: (EventType | null);
    severity?: (EventSeverity | null);
    title?: (string | null);
    description?: (string | null);
    source?: (EventSource | null);
    status?: (EventStatus | null);
    related_action_id?: (string | null);
};

export type MachineNoteCreate = {
    title: string;
    content: string;
    shift: NoteShift;
    impact?: (string | null);
    criticality?: NoteCriticality;
    machine_id: string;
};

export type MachineNotePublic = {
    title: string;
    content: string;
    shift: NoteShift;
    impact?: (string | null);
    criticality?: NoteCriticality;
    id: string;
    machine_id: string;
    created_by?: (string | null);
    created_at: string;
};

export type MachineNotesPublic = {
    data: Array<MachineNotePublic>;
    count: number;
};

export type MachineNoteUpdate = {
    title?: (string | null);
    content?: (string | null);
    shift?: (NoteShift | null);
    impact?: (string | null);
    criticality?: (NoteCriticality | null);
};

export type MachinePublic = {
    name: string;
    description?: (string | null);
    kep_tag_prefix?: (string | null);
    display_order?: number;
    machine_type?: (string | null);
    id: string;
    unit_id: string;
};

export type MachinesPublic = {
    data: Array<MachinePublic>;
    count: number;
};

export type MachineStatusesPublic = {
    data: Array<MachineStatusPublic>;
    count: number;
};

export type MachineStatusPublic = {
    timestamp?: string;
    status: OEEStatus;
    availability: number;
    performance: number;
    quality: number;
    raw_data?: (unknown | null);
    id: string;
    machine_id: string;
};

export type MachineTile = {
    name: string;
    description?: (string | null);
    kep_tag_prefix?: (string | null);
    display_order?: number;
    machine_type?: (string | null);
    id: string;
    unit_id: string;
    oee?: (OEESummary | null);
    active_alarm_count?: number;
};

export type MachineUpdate = {
    name?: (string | null);
    description?: (string | null);
    kep_tag_prefix?: (string | null);
    display_order?: (number | null);
    unit_id?: (string | null);
    machine_type?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NoteCriticality = 'low' | 'medium' | 'high';

export type NoteShift = 'morning' | 'afternoon' | 'night';

export type OEEStatus = 'green' | 'yellow' | 'red';

export type OEESummary = {
    availability?: (number | null);
    performance?: (number | null);
    quality?: (number | null);
    availability_status?: (OEEStatus | null);
    performance_status?: (OEEStatus | null);
    quality_status?: (OEEStatus | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnitCreate = {
    name: string;
    description?: (string | null);
    display_order?: number;
    department_id: string;
};

export type UnitPublic = {
    name: string;
    description?: (string | null);
    display_order?: number;
    id: string;
    department_id: string;
};

export type UnitsPublic = {
    data: Array<UnitPublic>;
    count: number;
};

export type UnitTile = {
    name: string;
    description?: (string | null);
    display_order?: number;
    id: string;
    department_id: string;
    oee?: (OEESummary | null);
    machine_count?: number;
    running_count?: number;
    warning_count?: number;
    stopped_count?: number;
    alarm_count?: number;
};

export type UnitUpdate = {
    name?: (string | null);
    description?: (string | null);
    display_order?: (number | null);
    department_id?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DemoSeedDemoDataData = {
    requestBody: DemoSeedRequest;
};

export type DemoSeedDemoDataResponse = (Message);

export type DemoClearDemoDataData = {
    machineId: string;
};

export type DemoClearDemoDataResponse = (Message);

export type DepartmentsReadDepartmentsData = {
    limit?: number;
    skip?: number;
};

export type DepartmentsReadDepartmentsResponse = (Array<DepartmentTile>);

export type DepartmentsCreateDeptData = {
    requestBody: DepartmentCreate;
};

export type DepartmentsCreateDeptResponse = (DepartmentPublic);

export type DepartmentsReadDepartmentData = {
    id: string;
};

export type DepartmentsReadDepartmentResponse = (DepartmentPublic);

export type DepartmentsUpdateDeptData = {
    id: string;
    requestBody: DepartmentUpdate;
};

export type DepartmentsUpdateDeptResponse = (DepartmentPublic);

export type DepartmentsDeleteDeptData = {
    id: string;
};

export type DepartmentsDeleteDeptResponse = (Message);

export type DepartmentsReadDepartmentUnitsData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type DepartmentsReadDepartmentUnitsResponse = (Array<UnitTile>);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LossCodeCategoriesReadLossCodeCategoriesData = {
    typeId?: (string | null);
};

export type LossCodeCategoriesReadLossCodeCategoriesResponse = (Array<LossCodeCategoryPublic>);

export type LossCodeCategoriesCreateCategoryData = {
    requestBody: LossCodeCategoryCreate;
};

export type LossCodeCategoriesCreateCategoryResponse = (LossCodeCategoryPublic);

export type LossCodeCategoriesUpdateCategoryData = {
    id: string;
    requestBody: LossCodeCategoryUpdate;
};

export type LossCodeCategoriesUpdateCategoryResponse = (LossCodeCategoryPublic);

export type LossCodeCategoriesDeleteCategoryData = {
    id: string;
};

export type LossCodeCategoriesDeleteCategoryResponse = (Message);

export type LossCodesReadLossCodeHierarchyResponse = (Array<LossCodeTypeWithHierarchy>);

export type LossCodesReadLossCodesData = {
    limit?: number;
    skip?: number;
};

export type LossCodesReadLossCodesResponse = (LossCodesPublic);

export type LossCodesCreateLossCodeEndpointData = {
    requestBody: LossCodeCreate;
};

export type LossCodesCreateLossCodeEndpointResponse = (LossCodePublic);

export type LossCodesReadLossCodeData = {
    id: string;
};

export type LossCodesReadLossCodeResponse = (LossCodePublic);

export type LossCodesUpdateLossCodeEndpointData = {
    id: string;
    requestBody: LossCodeUpdate;
};

export type LossCodesUpdateLossCodeEndpointResponse = (LossCodePublic);

export type LossCodesDeleteLossCodeData = {
    id: string;
};

export type LossCodesDeleteLossCodeResponse = (Message);

export type LossCodeTypesReadLossCodeTypesResponse = (Array<LossCodeTypePublic>);

export type LossEntriesReadLossEntriesData = {
    limit?: number;
    machineId?: (string | null);
    skip?: number;
};

export type LossEntriesReadLossEntriesResponse = (LossCodeEntriesPublic);

export type LossEntriesCreateLossEntryEndpointData = {
    requestBody: LossCodeEntryCreate;
};

export type LossEntriesCreateLossEntryEndpointResponse = (LossCodeEntryPublic);

export type LossEntriesReadLossEntryData = {
    id: string;
};

export type LossEntriesReadLossEntryResponse = (LossCodeEntryPublic);

export type LossEntriesUpdateLossEntryEndpointData = {
    id: string;
    requestBody: LossCodeEntryUpdate;
};

export type LossEntriesUpdateLossEntryEndpointResponse = (LossCodeEntryPublic);

export type LossEntriesDeleteLossEntryData = {
    id: string;
};

export type LossEntriesDeleteLossEntryResponse = (Message);

export type MachineActionsReadMachineActionsData = {
    machineId: string;
};

export type MachineActionsReadMachineActionsResponse = (MachineActionsPublic);

export type MachineActionsCreateActionData = {
    requestBody: MachineActionCreate;
};

export type MachineActionsCreateActionResponse = (MachineActionPublic);

export type MachineActionsUpdateActionData = {
    id: string;
    requestBody: MachineActionUpdate;
};

export type MachineActionsUpdateActionResponse = (MachineActionPublic);

export type MachineActionsDeleteActionData = {
    id: string;
};

export type MachineActionsDeleteActionResponse = (Message);

export type MachineEventsListEventsData = {
    eventType?: (EventType | null);
    limit?: number;
    machineId: string;
    skip?: number;
    status?: (EventStatus | null);
};

export type MachineEventsListEventsResponse = (MachineEventsPublic);

export type MachineEventsCreateEventData = {
    requestBody: MachineEventCreate;
};

export type MachineEventsCreateEventResponse = (MachineEventPublic);

export type MachineEventsUpdateEventData = {
    id: string;
    requestBody: MachineEventUpdate;
};

export type MachineEventsUpdateEventResponse = (MachineEventPublic);

export type MachineEventsDeleteEventData = {
    id: string;
};

export type MachineEventsDeleteEventResponse = (Message);

export type MachineNotesReadMachineNotesData = {
    machineId: string;
};

export type MachineNotesReadMachineNotesResponse = (MachineNotesPublic);

export type MachineNotesCreateNoteData = {
    requestBody: MachineNoteCreate;
};

export type MachineNotesCreateNoteResponse = (MachineNotePublic);

export type MachineNotesUpdateNoteData = {
    id: string;
    requestBody: MachineNoteUpdate;
};

export type MachineNotesUpdateNoteResponse = (MachineNotePublic);

export type MachineNotesDeleteNoteData = {
    id: string;
};

export type MachineNotesDeleteNoteResponse = (Message);

export type MachinesReadMachinesData = {
    limit?: number;
    skip?: number;
    unitId?: (string | null);
};

export type MachinesReadMachinesResponse = (MachinesPublic);

export type MachinesCreateMachineEndpointData = {
    requestBody: MachineCreate;
};

export type MachinesCreateMachineEndpointResponse = (MachinePublic);

export type MachinesReadMachineData = {
    id: string;
};

export type MachinesReadMachineResponse = (MachinePublic);

export type MachinesUpdateMachineEndpointData = {
    id: string;
    requestBody: MachineUpdate;
};

export type MachinesUpdateMachineEndpointResponse = (MachinePublic);

export type MachinesDeleteMachineData = {
    id: string;
};

export type MachinesDeleteMachineResponse = (Message);

export type MachinesReadMachineStatusTimelineData = {
    fromTime?: (string | null);
    id: string;
    toTime?: (string | null);
};

export type MachinesReadMachineStatusTimelineResponse = (MachineStatusesPublic);

export type MachinesReadMachineLossEntriesData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type MachinesReadMachineLossEntriesResponse = (LossCodeEntriesPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UnitsReadUnitsData = {
    departmentId?: (string | null);
    limit?: number;
    skip?: number;
};

export type UnitsReadUnitsResponse = (UnitsPublic);

export type UnitsCreateUnitEndpointData = {
    requestBody: UnitCreate;
};

export type UnitsCreateUnitEndpointResponse = (UnitPublic);

export type UnitsReadUnitData = {
    id: string;
};

export type UnitsReadUnitResponse = (UnitPublic);

export type UnitsUpdateUnitEndpointData = {
    id: string;
    requestBody: UnitUpdate;
};

export type UnitsUpdateUnitEndpointResponse = (UnitPublic);

export type UnitsDeleteUnitData = {
    id: string;
};

export type UnitsDeleteUnitResponse = (Message);

export type UnitsReadUnitMachinesTilesData = {
    id: string;
    limit?: number;
    skip?: number;
};

export type UnitsReadUnitMachinesTilesResponse = (Array<MachineTile>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type ViewsReadViewsData = {
    entityId?: (string | null);
    level?: (HierarchyLevel | null);
    limit?: number;
    skip?: number;
};

export type ViewsReadViewsResponse = (HierarchyViewsPublic);

export type ViewsCreateViewEndpointData = {
    requestBody: HierarchyViewCreate;
};

export type ViewsCreateViewEndpointResponse = (HierarchyViewPublic);

export type ViewsReadViewData = {
    id: string;
};

export type ViewsReadViewResponse = (HierarchyViewPublic);

export type ViewsUpdateViewEndpointData = {
    id: string;
    requestBody: HierarchyViewUpdate;
};

export type ViewsUpdateViewEndpointResponse = (HierarchyViewPublic);

export type ViewsDeleteViewData = {
    id: string;
};

export type ViewsDeleteViewResponse = (Message);