/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutDepartmentsDepartmentIdRouteImport } from './routes/_layout/departments/$departmentId'
import { Route as LayoutConfigUnitsRouteImport } from './routes/_layout/config/units'
import { Route as LayoutConfigMachinesRouteImport } from './routes/_layout/config/machines'
import { Route as LayoutConfigLossCodesRouteImport } from './routes/_layout/config/loss-codes'
import { Route as LayoutConfigDepartmentsRouteImport } from './routes/_layout/config/departments'
import { Route as LayoutDepartmentsDepartmentIdIndexRouteImport } from './routes/_layout/departments/$departmentId/index'
import { Route as LayoutDepartmentsDepartmentIdUnitsUnitIdRouteImport } from './routes/_layout/departments/$departmentId/units/$unitId'
import { Route as LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRouteImport } from './routes/_layout/departments/$departmentId/units/$unitId/index'
import { Route as LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRouteImport } from './routes/_layout/departments/$departmentId/units/$unitId/machines/$machineId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDepartmentsDepartmentIdRoute =
  LayoutDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutConfigUnitsRoute = LayoutConfigUnitsRouteImport.update({
  id: '/config/units',
  path: '/config/units',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigMachinesRoute = LayoutConfigMachinesRouteImport.update({
  id: '/config/machines',
  path: '/config/machines',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigLossCodesRoute = LayoutConfigLossCodesRouteImport.update({
  id: '/config/loss-codes',
  path: '/config/loss-codes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConfigDepartmentsRoute = LayoutConfigDepartmentsRouteImport.update({
  id: '/config/departments',
  path: '/config/departments',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDepartmentsDepartmentIdIndexRoute =
  LayoutDepartmentsDepartmentIdIndexRouteImport.update({
    id: '/_layout/departments/$departmentId/',
    path: '/',
    getParentRoute: () => LayoutDepartmentsDepartmentIdRoute,
  } as any)
const LayoutDepartmentsDepartmentIdUnitsUnitIdRoute =
  LayoutDepartmentsDepartmentIdUnitsUnitIdRouteImport.update({
    id: '/units/$unitId',
    path: '/units/$unitId',
    getParentRoute: () => LayoutDepartmentsDepartmentIdRoute,
  } as any)
const LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute =
  LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRouteImport.update({
    id: '/_layout/departments/$departmentId/units/$unitId/',
    path: '/',
    getParentRoute: () => LayoutDepartmentsDepartmentIdUnitsUnitIdRoute,
  } as any)
const LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute =
  LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRouteImport.update({
    id: '/machines/$machineId',
    path: '/machines/$machineId',
    getParentRoute: () => LayoutDepartmentsDepartmentIdUnitsUnitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/config/departments': typeof LayoutConfigDepartmentsRoute
  '/config/loss-codes': typeof LayoutConfigLossCodesRoute
  '/config/machines': typeof LayoutConfigMachinesRoute
  '/config/units': typeof LayoutConfigUnitsRoute
  '/departments/$departmentId': typeof LayoutDepartmentsDepartmentIdRouteWithChildren
  '/departments/$departmentId/': typeof LayoutDepartmentsDepartmentIdIndexRoute
  '/departments/$departmentId/units/$unitId': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRouteWithChildren
  '/departments/$departmentId/units/$unitId/': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute
  '/departments/$departmentId/units/$unitId/machines/$machineId': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/config/departments': typeof LayoutConfigDepartmentsRoute
  '/config/loss-codes': typeof LayoutConfigLossCodesRoute
  '/config/machines': typeof LayoutConfigMachinesRoute
  '/config/units': typeof LayoutConfigUnitsRoute
  '/departments/$departmentId': typeof LayoutDepartmentsDepartmentIdRouteWithChildren
  '/departments/$departmentId/': typeof LayoutDepartmentsDepartmentIdIndexRoute
  '/departments/$departmentId/units/$unitId': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRouteWithChildren
  '/departments/$departmentId/units/$unitId/': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute
  '/departments/$departmentId/units/$unitId/machines/$machineId': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/config/departments': typeof LayoutConfigDepartmentsRoute
  '/_layout/config/loss-codes': typeof LayoutConfigLossCodesRoute
  '/_layout/config/machines': typeof LayoutConfigMachinesRoute
  '/_layout/config/units': typeof LayoutConfigUnitsRoute
  '/_layout/departments/$departmentId': typeof LayoutDepartmentsDepartmentIdRouteWithChildren
  '/_layout/departments/$departmentId/': typeof LayoutDepartmentsDepartmentIdIndexRoute
  '/_layout/departments/$departmentId/units/$unitId': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRouteWithChildren
  '/_layout/departments/$departmentId/units/$unitId/': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute
  '/_layout/departments/$departmentId/units/$unitId/machines/$machineId': typeof LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/config/departments'
    | '/config/loss-codes'
    | '/config/machines'
    | '/config/units'
    | '/departments/$departmentId'
    | '/departments/$departmentId/'
    | '/departments/$departmentId/units/$unitId'
    | '/departments/$departmentId/units/$unitId/'
    | '/departments/$departmentId/units/$unitId/machines/$machineId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/config/departments'
    | '/config/loss-codes'
    | '/config/machines'
    | '/config/units'
    | '/departments/$departmentId'
    | '/departments/$departmentId/'
    | '/departments/$departmentId/units/$unitId'
    | '/departments/$departmentId/units/$unitId/'
    | '/departments/$departmentId/units/$unitId/machines/$machineId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/config/departments'
    | '/_layout/config/loss-codes'
    | '/_layout/config/machines'
    | '/_layout/config/units'
    | '/_layout/departments/$departmentId'
    | '/_layout/departments/$departmentId/'
    | '/_layout/departments/$departmentId/units/$unitId'
    | '/_layout/departments/$departmentId/units/$unitId/'
    | '/_layout/departments/$departmentId/units/$unitId/machines/$machineId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/departments/$departmentId': {
      id: '/_layout/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof LayoutDepartmentsDepartmentIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/departments/$departmentId/': {
      id: '/_layout/departments/$departmentId/'
      path: '/'
      fullPath: '/departments/$departmentId/'
      preLoaderRoute: typeof LayoutDepartmentsDepartmentIdIndexRouteImport
      parentRoute: typeof LayoutDepartmentsDepartmentIdRoute
    }
    '/_layout/config/units': {
      id: '/_layout/config/units'
      path: '/config/units'
      fullPath: '/config/units'
      preLoaderRoute: typeof LayoutConfigUnitsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config/machines': {
      id: '/_layout/config/machines'
      path: '/config/machines'
      fullPath: '/config/machines'
      preLoaderRoute: typeof LayoutConfigMachinesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config/loss-codes': {
      id: '/_layout/config/loss-codes'
      path: '/config/loss-codes'
      fullPath: '/config/loss-codes'
      preLoaderRoute: typeof LayoutConfigLossCodesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/config/departments': {
      id: '/_layout/config/departments'
      path: '/config/departments'
      fullPath: '/config/departments'
      preLoaderRoute: typeof LayoutConfigDepartmentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/departments/$departmentId/units/$unitId': {
      id: '/_layout/departments/$departmentId/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/departments/$departmentId/units/$unitId'
      preLoaderRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRouteImport
      parentRoute: typeof LayoutDepartmentsDepartmentIdRoute
    }
    '/_layout/departments/$departmentId/units/$unitId/': {
      id: '/_layout/departments/$departmentId/units/$unitId/'
      path: '/'
      fullPath: '/departments/$departmentId/units/$unitId/'
      preLoaderRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRouteImport
      parentRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRoute
    }
    '/_layout/departments/$departmentId/units/$unitId/machines/$machineId': {
      id: '/_layout/departments/$departmentId/units/$unitId/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/departments/$departmentId/units/$unitId/machines/$machineId'
      preLoaderRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRouteImport
      parentRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRoute
    }
  }
}

interface LayoutDepartmentsDepartmentIdUnitsUnitIdRouteChildren {
  LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute
  LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute
}

const LayoutDepartmentsDepartmentIdUnitsUnitIdRouteChildren: LayoutDepartmentsDepartmentIdUnitsUnitIdRouteChildren =
  {
    LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute:
      LayoutDepartmentsDepartmentIdUnitsUnitIdIndexRoute,
    LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute:
      LayoutDepartmentsDepartmentIdUnitsUnitIdMachinesMachineIdRoute,
  }

const LayoutDepartmentsDepartmentIdUnitsUnitIdRouteWithChildren =
  LayoutDepartmentsDepartmentIdUnitsUnitIdRoute._addFileChildren(
    LayoutDepartmentsDepartmentIdUnitsUnitIdRouteChildren,
  )

interface LayoutDepartmentsDepartmentIdRouteChildren {
  LayoutDepartmentsDepartmentIdIndexRoute: typeof LayoutDepartmentsDepartmentIdIndexRoute
  LayoutDepartmentsDepartmentIdUnitsUnitIdRoute: typeof LayoutDepartmentsDepartmentIdUnitsUnitIdRouteWithChildren
}

const LayoutDepartmentsDepartmentIdRouteChildren: LayoutDepartmentsDepartmentIdRouteChildren =
  {
    LayoutDepartmentsDepartmentIdIndexRoute:
      LayoutDepartmentsDepartmentIdIndexRoute,
    LayoutDepartmentsDepartmentIdUnitsUnitIdRoute:
      LayoutDepartmentsDepartmentIdUnitsUnitIdRouteWithChildren,
  }

const LayoutDepartmentsDepartmentIdRouteWithChildren =
  LayoutDepartmentsDepartmentIdRoute._addFileChildren(
    LayoutDepartmentsDepartmentIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutConfigDepartmentsRoute: typeof LayoutConfigDepartmentsRoute
  LayoutConfigLossCodesRoute: typeof LayoutConfigLossCodesRoute
  LayoutConfigMachinesRoute: typeof LayoutConfigMachinesRoute
  LayoutConfigUnitsRoute: typeof LayoutConfigUnitsRoute
  LayoutDepartmentsDepartmentIdRoute: typeof LayoutDepartmentsDepartmentIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutConfigDepartmentsRoute: LayoutConfigDepartmentsRoute,
  LayoutConfigLossCodesRoute: LayoutConfigLossCodesRoute,
  LayoutConfigMachinesRoute: LayoutConfigMachinesRoute,
  LayoutConfigUnitsRoute: LayoutConfigUnitsRoute,
  LayoutDepartmentsDepartmentIdRoute:
    LayoutDepartmentsDepartmentIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
